### PR TITLE
Register trip

### PR DESCRIPTION
**Pull request by maulikdhameliya**
Trip related screen changes :
-> Home Screen UI Display Text Change
-> Search Trip UI
 -> Search Trip Result UI :
   - Trip Result View
    - Trip expanded View
   - Contact Info Modal View
-> Register Ride UI & Firestore Entry of RoundTrip/SingleTrip
-> Code to add trip in firebase after Register Ride
-> Trip Information page after Registering Ride

### CODE REVIEW

**Comment by bhaskerreddyb** [comment]
At a high level, it looks good
1) We should fit this into the screen, without scrolling.
I see there is a lot of space after the header
We can reduce input box hights
2) Provide Companionship and Carry documents can be parallel ( we don't have an extra step here)
3) For a visual representation, change oneway and Roundtrip with a radio button.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_radio

**Comment by maulikdhameliya** [comment]
@bhaskerreddyb below changes are done please verify 

- Registration Page UI changes
- Added DatePicker
- Search Trip result UI changes
- Search Airport functionality 
- Search Airlines functionality
- Submit Data to Firestore

**Comment by maulikdhameliya** [comment]
1) Navigation header is too big, that's why we can fit in single screen
Regarding fitting into screen, I see header occupies 20% of the screen
I think input height can be reduced Like phone input
And spaces between input boxes
2) I think you can reduce, the size of height header
3) I am still not seeing radio buttons for Round Trip and Oneway trip
For Radio button fix on ios,  you can do something like this
<RadioButton.Android
                color="#0E8B7D"
                value="roundTrip"
                status={tripTypeValue === 'roundTrip' ? 'checked' : 'unchecked'}
                onPress={() => {
                  setTripTypeValue('roundTrip');
                }}
              />
4) On choosing Airport from "starting From"box, I should click on explicitly on icon. I think it should work on clicking on any where on that boz
5) This applies to all boxes same as point 4
6) We can remove search icon Submit button
7) One more thing, I think we should include ios/Podfile.lock as part of the commit
8) for Oneway, don't show second boc for date instead of disable

@bhaskerreddyb above points fixed.

Notes regarding oneway trip, I hide return date and make start date occupy full width as it was not looking nice

**Comment by maulikdhameliya** [comment]
@bhaskerreddyb 
- add search functionality
- add current user upcoming trips and past trips

there are some things pending like validation before submitting trip, adding X button on the selection screen

**Pull request merged**
